version: '2'
services:
  front:
    image: amiotisse/ubsunu-front:RC1
    ports:
      - 80:80
    depends_on:
      - alphau
    restart: always

  mailer:
    image: amiotisse/ubsunu-mailer:RC1
    restart: always

  alphau:
    image: himnabil/alphau-server:RC1
    depends_on:
      - mongodb
    restart: always

  profile:
    image: amiotisse/ubsunu-profile:RC1
    depends_on:
      - alphau
      - mongodb
    restart: always

  marks:
    image: amiotisse/ubsunu-marks:RC1
    depends_on:
      - alphau
      - mailer
      - mongodb
    restart: always

  mongodb:
    image: mongo
    restart: always
    volumes:
      - /data:/data/db
