version: '2'
services:
  front:
    image: amiotisse/ubsunu-front:RC1
    ports:
      - 80:80
    depends_on:
      - alphau
    restart: always

  alphau:
    image: himnabil/alphau-server:RC1
    depends_on:
      - mongodb
    restart: always

  mongodb:
    image: mongo
  restart: always
